Beautify Workspace

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,54 +15,49 @@ jobs:
       GitHubName: "rokibhasansagar"
 
     steps:
+      # Check Git Configs Set Or Not (Temporary)
+      - run: git config -l && git config --global -l
+      # Checkout The Workflow, Shallow Clone
       - uses: actions/checkout@v2
-
+        with:
+          token: "${{ secrets.GH_TOKEN }}"
+          fetch-depth: "1"
+      # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main
-
-      - name: Install expect
-        run: |
-          sudo apt-get install -qy expect
-
-      - name: cloning repo
-        run: |
-          git config --global user.email $GitHubMail
-          git config --global user.name $GitHubName
-          expect -c "
-          spawn git clone https://github.com/$GitHubName/${{ secrets.MIRROR_TOOL }} -b production source
-          expect \"Username\"        
-          send \"${GitHubName}\r\"
-          expect \"Password\"        
-          send \"${{ secrets.GH_TOKEN }}\r\"
-          set timeout -1
-          catch wait result
-          interact"
-
+      # Checkout The Secret Mirror Tool
+      - uses: actions/checkout@v2
+        with:
+          repository: "${GitHubName}/${{ secrets.MIRROR_TOOL }}"
+          ref: "production"
+          token: "${{ secrets.GH_TOKEN }}"
+          path: "source"
+          fetch-depth: "1"
+      # Compile The Mirroring Docker Container
       - name: compilation
         run: |
-          cd source
+          cd source || exit 1
           docker container prune --force || true
-          docker build . -t mirror-bot
-
+          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
+          docker image ls
+      # Run The Mirroring Docker Container
       - name: running Docker
         continue-on-error: true
         timeout-minutes: 320
         run: |
-          docker run mirror-bot
-
-      - name: Loop workflow
-        continue-on-error: true
+          docker run --privileged --rm -i mirror-bot
+      # Self Checkout, Again For Looping
+      - uses: actions/checkout@v2
+        with:
+          repository: "${GITHUB_REPOSITORY}"
+          token: "${{ secrets.GH_TOKEN }}"
+          path: "loop"
+          fetch-depth: "0"
+      # Add Random Data & Push The Looper
+      - name: Loop Commit
         run: |
-          git clone https://${{ secrets.GH_TOKEN }}@github.com/$GitHubName/TGMirrorLooper loop
-          cd loop
+          cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
-          git commit -as -m "Looping at $(date -u +%s)"
-          expect -c "
-          spawn git push -f
-          expect \"Username\"        
-          send \"${GitHubName}\r\"
-          expect \"Password\"        
-          send \"${{ secrets.GH_TOKEN }}\r\"
-          expect \"main -> main\"
-          set timeout -10
-          interact"
+          git commit -as -m "Looping at $(date -u +%D-%T%P)"
+          git push -f origin main
+          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main"
